version: '3'

services:

  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d diploma" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: python app.py
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
